version: 2

models:
  - name: stg_yellow_taxi
    description: "Staging layer for yellow taxi data with standardized column names"
    columns:
      - name: vendor_id
        description: "A code indicating the TPEP provider (1=CMT, 2=VeriFone)"
      - name: pickup_datetime
        description: "The date and time when the meter was engaged"
      - name: dropoff_datetime
        description: "The date and time when the meter was disengaged"
      - name: passenger_count
        description: "The number of passengers in the vehicle"
      - name: trip_distance_miles
        description: "The elapsed trip distance in miles"

  - name: dim_vendor
    description: "Dimension table for taxi vendors"
    columns:
      - name: vendor_id
        tests:
          - unique
          - not_null

  - name: dim_payment_type
    description: "Dimension table for payment types"
    columns:
      - name: payment_type_id
        tests:
          - unique
          - not_null

  - name: dim_rate_code
    description: "Dimension table for rate codes"
    columns:
      - name: rate_code_id
        tests:
          - unique
          - not_null

  - name: dim_date
    description: "Date dimension spanning 2009-2030"
    columns:
      - name: date_key
        tests:
          - unique
          - not_null

  - name: dim_time
    description: "Time dimension for hours of the day"
    columns:
      - name: hour_key
        tests:
          - unique
          - not_null

  - name: fct_trips
    description: "Fact table containing cleaned and validated trip data"
    columns:
      - name: trip_id
        description: "Unique identifier for each trip (may have collisions for identical trips)"
        tests:
          - unique:
              severity: warn
          - not_null
      - name: pickup_datetime
        tests:
          - not_null
      - name: dropoff_datetime
        tests:
          - not_null
      - name: pickup_location_id
        description: "TLC Taxi Zone where the trip began"
      - name: dropoff_location_id
        description: "TLC Taxi Zone where the trip ended"
      - name: total_amount
        description: "Total amount charged to passengers"
      - name: has_data_quality_issue
        description: "Flag indicating potential data quality problems"
